### ISSUE TITLE
MS24 one paper on data standards (May 2024)

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/BioDT#10]
MS24 Publication on advancement and application of the event core, material samples, and the species interaction/resource relationship domain data model (M24 = May 2024)
Means of verification: Publication submitted.

Milestone 24 describes a paper on data standards to be submitted in May 2024.

Actions
* Update the [BioDT Research publication roadmap](https://wiki.eduuni.fi/x/yzIiG) with information about the planned paper.

Lead Carrie (TBC?)

**Comment by dagendresen** [comment]
See also https://www.nhm.uio.no/english/research/projects/biodt/slides/2023-06-ontologies-uio-data.pdf

**Comment by cjandrew** [comment]
If you, @dagendresen, can send reference publications, for examples of how to start planning this task (when you have time)?

**Comment by dagendresen** [comment]
The [Darwin Core](https://dwc.tdwg.org/terms/) paper ([Wieczorek et al. 2012](https://doi.org/10.1371/journal.pone.0029715)) is a good starting point. We had a sequence of Darwin Core related workshops and published workshop reports together with the Genomic Standards Consortium (GSC) that I think could be good inspiration for the MS24 paper ([Wieczorek et al. 2014](https://doi.org/10.4056/sigs.4898640), [Walls et al. 2014](https://doi.org/10.1186%2F1944-3277-9-17), and more). These workshops lead to a more high-profile PLoS One paper ([Walls et al. 2014](https://doi.org/10.1371/journal.pone.0089606)) introducing a new Biological Collections Ontology (BCO) which I think is an important reference to understand the semantic meaning of the Darwin Core classes. The Darwin-SW ([Baskauf and Webb 2016](https://doi.org/10.3233/SW-150203), see also [Baskauf et al 2016](https://doi.org/10.3233/SW-150199)) is another very useful ontology for understanding the Darwin Core classes and guide work we could progress further in BioDT. The Humboldt Core ([Guralnick et al 2018](https://doi.org/10.1111/ecog.02942)) could also be a relevant data standard in particular for connecting eLTER data to the BioDT. Regarding the Darwin Core [MeasurementOrFact](http://rs.tdwg.org/dwc/terms/MeasurementOrFact) and [ResourceRelationship](http://rs.tdwg.org/dwc/terms/ResourceRelationship) mentioned in MS24, I think that the  improved "extended Measurement or Fact" (eMoF) developed by marine data community (OBIS) and described by ([De Pooter et al. 2017](https://doi.org/10.3897/BDJ.5.e10989)) will prove to be very useful for many of our BioDT use cases. I think that this eMoF and usage together with the Darwin Core Resource Relationship will be important for many of the BioDT use cases (see also slides [Endresen 2018](http://doi.org/10.13140/RG.2.2.16667.36641)). Mostly relevant for the agrobiodiversty data standards and our CWR pDT I have tried to summarize an overview in a book chapter ([Endresen 2017](http://urn.nb.no/URN:NBN:no-67672)) which might be a good start for these agro standards if we include also this topic in the MS24 paper.

**Comment by dagendresen** [comment]
Pensoft RIO could be a relevant outlet for a paper on data standards recommendations from the BioDT perspective
The [RIO collection of papers from](https://riojournal.com/topical_collection/105/) the [BICIKL project (2021-2024)](https://cordis.europa.eu/project/id/101007492) could be relevant to look at (many recent and relevant papers here on data standards).

**Comment by cjandrew** [comment]
I created the Eduuwiki page you requested, if you would like to add any of the above information there: https://wiki.eduuni.fi/pages/viewpage.action?pageId=440705636

**Comment by cjandrew** [comment]
But are you sure you are not confusing your own interests with the goal of the Milestone? 

I do not see anything about data standards in the title: _MS24 Publication on advancement and application of the event core, material samples, and the species interaction/resource relationship domain data model_ 

Thus it is still very unclear to me what the subject of the MS24 report would be on.

**Comment by dagendresen** [comment]
We can discuss how to address the milestone MS24 paper in our meeting tomorrow. We might also ask Dmitry and Sharif how they read the milestone :-)

**Comment by dagendresen** [comment]
One approach could be to look at how the event core, material sample/entity core, and species interactions concepts (classes) are implemented in the Darwin Core standard (and other data standards/ontologies). And how well these implementations in the data standards themselves are suitable for our needs in the BioDT use cases. To maybe even suggest improvements to the Darwin Core data standard or other relevant data standards/ontologies themselves. (This was my thinking of how to address MS24).

Another approach could of course be to look at how (and even if) the use cases make use of these event, material entity, and species interaction concepts. And maybe suggest improvements to how the use cases can make better use of these concepts from Darwin Core (or other standards). (Maybe this second approach is closer to how you are thinking of MS24?).

I am sure either way will be a perfectly relevant response to MS24!

**Comment by dagendresen** [comment]
Preprint published
https://doi.org/10.48550/arXiv.2405.19857
