### ISSUE TITLE
BrAPI hackathon 23-27 October 2023

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/BioDT#4]
# BrAPI Virtual hackathon 23-27 October

BrAPI - plant breeding API network
https://brapi.org/events/hackathon#agenda-section

We might want to register the CWR pDT as a project at the hackathon?
https://brapi.org/events/hackathon#projects-section

BrAPI entity diagram UML
https://plantbreeding.github.io/brapi-ontology/uml.html

**Comment by ErikKusch** [comment]
Event happened. @ErikKusch attended.
