### ISSUE TITLE
BioDT WP7 representative from UiO

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/BioDT#6]
In WP7 (end-users) we (UiO) have task participation for
Task 7.1 RI requirements (bioRI as the end-user, etc)
Task 7.3 Tailored end-user training
This overlaps in part with our own task 4.3.1.

For the [formation of the pDT teams](https://wiki.eduuni.fi/x/6bVzEQ), WP7 asks for representatives for WP7.
Would you, @ErikKusch be in agreement with being listed as the WP7 representative for the DNA detected pDTs lead by GBIFS (pDT 4.1.2.2)? These pDTs are also related to our CWR pDT (classified as DNA-detected biodiversity pDTs).
See minutes from today's (2023-09-07) WP7 call: https://wiki.eduuni.fi/x/exuZFw
See emerging pDT teams here: https://wiki.eduuni.fi/x/6bVzEQ

**Comment by dagendresen** [comment]
There is also the question of our WP2 representative while Marcella is on leave. We contribute to task 2.3 (widening user uptake). This task is stated as shared/in coordination with WP7. However, likely much less overlapping with our task 4.3.1 (in my understanding). I believe that Cathy has agreed to represent us in WP2 and that this would be sufficient?

**Comment by ErikKusch** [comment]
Hiya,

I am afraid I have not interacted with any aspect of DNA or genetics since my B.Sc. days and wonder if someone else in our team might be better suited for this? What concrete work tasks would this representation in the pDT entail? 

I have a feeling I am about to get majorly busy with coding for our CWR pDT (effectively becoming a WP6-like contributor as WP6 finds themselves stretched too thin to add a representative) and have additionally been invited to contribute to the GRASSMIND and invasive species DT while at ECEM 2023. That makes me weary of over-committing.

How pressed are we to assign someone from WP7 to this right now and does it have to be someone from UiO?

**Comment by cjandrew** [comment]
Hei, I have worked considerably with DNA & possibly could help out -- not sure how much work this would entail beyond attending meetings and filling in the group on updates? If not much more than that, then I would probably not have a problem to help out. Do as you see fit, it is fine for me to help out, or have someone else do it! But maybe my qualifications line up a bit better than Erik's?

**Comment by dagendresen** [comment]
It is not a problem to say no to representing WP7 in the pDT teams :-)

Great if @cjandrew  is interested in and qualified for representing WP7 in these DNA-detected pDT! (Thanks!). Fits also well with deputy lead for the CWR pDT? (For the CWR pDT I think we do want to hold on to Tomas as the WP7 representative?). Representing WP7 in the pDT teams would be most efficient if participating in the monthly WP7 Zoom calls (like the one today), or coordinating closely with Erik who likely would want to participate anyway because of the strong task 7.1 overlap (?).

Apropos priority of time, we need to be mindful of where our PMs are distributed. We as UiO has 
|     | WP2 | WP4 | WP5 | WP6  | WP7 |
|-----|-----|-----|-----|------|-----|
| UiO | 3.5 PM | 58 PM  | 12 PM  | zero | 8 PM   |

**Comment by ErikKusch** [comment]
I'd be happy to share this task with @cjandrew! I imagine your knowledge of the biological topic and my task of catching RI requirements would fit well with what is needed here.

**Comment by cjandrew** [comment]
I am now signed up for the pDTs WP7 for 
A) 4.1.2.2 DNA detected biodiversity, poorly known habitats 
B) 4.1.2.2.2 DNA detected biodiversity, poorly known habitats - phylogenetic diversity
and will join in the WP7 meetings for that specific reason (to bridge between WP7 & the pDTs)!

**Comment by dagendresen** [comment]
Thanks!!
@cjandrew you may also want to join the wp7-biodt@postit.csc.fi mailing list.
See mailing list guidelines at: https://wiki.eduuni.fi/x/I8HLE
