### ISSUE TITLE
BioDT WP2 representative from UiO

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/BioDT#7]
Apropos https://github.com/uio-mana/BioDT/issues/6

There is also the question of our WP2 representative while Marcella is on leave. We contribute to task 2.3 (widening user uptake). This task is stated as shared/in coordination with WP7. However, likely much less overlapping with our task 4.3.1 (in my understanding). I believe that Cathy has agreed to represent us in WP2 and that this would be sufficient?

Are you @ErikKusch normally participating in the WP2 Zoom calls (like the one today, after the WP7 call)?

**Comment by ErikKusch** [comment]
Yes, I usually participate in these and am currently getting Cathy up to speed so she can fully take over for me on this representation.

**Comment by dagendresen** [comment]
Great!! Could you also remind her to attend the WP2 calls when you have a chance? (I will too!)
