### ISSUE TITLE
FDOs for software, talk 22 Sept 2023

### ISSUE THREAD

**Issue by dagendresen** [uio-mana/BioDT#8]
Open FDO Lecture
Should software objects be FDOs?
Dr. Daniel Katz, NCSA, U Illinois
22. September 2023 15.00 Amsterdam Time

Agenda:
https://drive.google.com/file/d/1e9NpxCOY6LBxrG5QXkGr29LdlE7M39Yj/view?usp=sharing

See also: FAIR Principles for Research Software (FAIR4RS Principles)
https://doi.org/10.15497/RDA00068

**Comment by ErikKusch** [comment]
Event happened
